# Site settings
title: Philo.log
email: write.to.philo.log@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this website is a simple portfolio of Philo.log's works.
baseurl: "" # the subpath of your site, e.g. /blog
logo: #"/images/logo/philolog_logo.png"
url: "https://philolog.github.io/" # the base hostname & protocol for your site
twitter_username: Philolog
github_username:  Philolog
google_analytics: G-4KMKFQMLFQ

# Build settings
markdown: kramdown
permalink: pretty
