# Site settings
title: Philo.log
email: write.to.philo.log@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is a short portfolio of Philo.log's works..
baseurl: "" # the subpath of your site, e.g. /blog
logo: "/images/logo/philolog_logo.png"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Philolog
github_username:  Philolog

# Build settings
markdown: kramdown
permalink: pretty
